using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using UIKWindow = Content.Client.UIKit.Controls.UIKWindow;


namespace Content.Client._Shitmed.Antags.Abductor;
[GenerateTypedNameReferences]
public sealed partial class AbductorConsoleWindow : UIKWindow
{
    public AbductorConsoleWindow() => RobustXamlLoader.Load(this);
}
