using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using UIKWindow = Content.Client.UIKit.Controls.UIKWindow;


namespace Content.Client.Mapping;

[GenerateTypedNameReferences]
public sealed partial class MappingVisibilityWindow : UIKWindow
{
    public MappingVisibilityWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

