using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using UIKWindow = Content.Client.UIKit.Controls.UIKWindow;


namespace Content.Client._Shitmed.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : UIKWindow
{
    public SurgeryWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
