using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using UIKWindow = Content.Client.UIKit.Controls.UIKWindow;


namespace Content.Client.Chemistry.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class TransferAmountWindow : UIKWindow
    {
        public TransferAmountWindow()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
