using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using UIKWindow = Content.Client.UIKit.Controls.UIKWindow;


namespace Content.Client.Administration.UI.Notes;

[GenerateTypedNameReferences]
public sealed partial class AdminNotesWindow : UIKWindow
{
    public AdminNotesWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetTitlePlayer(string playerName)
    {
        Title = Loc.GetString("admin-notes-title", ("player", playerName));
    }
}
